name = "GenomiccWorkflows"
uuid = "60113979-12f4-4738-9cbb-b1f052251c35"
authors = ["Olivier Labayle <olabayle@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GeneticsMakie = "8ca62643-82d8-47b5-a233-a06d1654fb35"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownTables = "1862ce21-31c7-451e-824c-f20fa3f90fa2"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
ArgParse = "1.2.0"
BufferedStreams = "1.2.2"
CSV = "0.10.15"
CairoMakie = "0.12,0.13.1"
CodecZlib = "0.7.7"
DataFrames = "1.7.0"
DelimitedFiles = "1.9.1"
Downloads = "1.6.0"
GeneticsMakie = "0.2.3"
HTTP = "1.10.15"
JSON = "0.21.4"
Literate = "2.20.1"
MLJBase = "1.8.1"
MLJModels = "0.17.9"
Markdown = "1.11.0"
MarkdownTables = "1.1.0"
PackageCompiler = "2.2.0"
Random = "1.11.0"
Statistics = "1.11.1"
Tables = "1.12.0"
YAML = "0.4.13"
ZipFile = "0.10.1"
julia = "1.11"
